# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd4ede062b1f6d0c513e907dc63dcb641f4799eee10e4afdbd4e2ce05d0c490dbd40122dd234301e838550c9a2d5c2a4c9fef33f4490117517b06dae59d2445

test:
  secret_key_base: 21f8e3602d79a8414f4c7d6aae90f21a8ebf54020fe8f4c7c1a0d10e2c01af2227cf22d1b26479fe226b20337f403d7d1bfd518c3ebdaae29877fe7e90129ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
